services:
  services:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru

volumes:
  pgdata:
  redisdata:
